name: Release
on:
    # schedule:
    #     - cron: '0 12 * * 1-5' # At 12:00 UTC on every day-of-week from Monday to Friday

    # manual trigger
    workflow_dispatch:

jobs:
    bump_version:
        name: Bump Version
        runs-on: ubuntu-latest
        outputs:
            new_tag: ${{ steps.github_tag_action.outputs.new_tag }}
            changelog: ${{ steps.github_tag_action.outputs.changelog }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Bump version and push tag
              id: github_tag_action
              uses: mathieudutour/github-tag-action@331898d5052eedac9b15fec867b5ba66ebf9b692
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  release_branches: .*

    create_release:
        name: Create Release
        runs-on: ubuntu-latest
        needs: bump_version
        if: ${{ needs.bump_version.outputs.new_tag != null }}
        env:
            SOURCE_DIR: 'build'
            REACT_APP_GRAPH_API_URLS: ${{ secrets.REACT_APP_GRAPH_API_URLS_PRODUCTION }}
            REACT_APP_NETWORK_ID: ${{ secrets.REACT_APP_NETWORK_ID_PRODUCTION }}
            REACT_APP_NETWORK_URL: ${{ secrets.REACT_APP_NETWORK_URL_PRODUCTION }}
            REACT_APP_COIN_TICKER_PRODUCTION: ${{ secrets.REACT_APP_COIN_TICKER_PRODUCTION }}
            REACT_APP_SYSTEM_STATUS: ${{ secrets.REACT_APP_SYSTEM_STATUS }}
            REACT_APP_GOOGLE_ANALYTICS_ID: ${{ secrets.REACT_APP_GOOGLE_ANALYTICS_ID_PRODUCTION }}
            REACT_APP_SHOW_AUCTIONS: ${{ secrets.REACT_APP_SHOW_AUCTIONS_PRODUCTION }}
            REACT_APP_WYRE_WORKER: ${{ secrets.REACT_APP_WYRE_WORKER }}

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up node
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Build the app
              run: yarn build

            - name: Deploy to Github Pages 🚀
              uses: JamesIves/github-pages-deploy-action@3.7.1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages # The branch the action should deploy to.
                  FOLDER: build # The folder the action should deploy.
                  CLEAN: true # Automatically remove deleted files from the deploy branch

            - name: Create GitHub Release
              id: create_release
              uses: actions/create-release@v1.1.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ needs.bump_version.outputs.new_tag }}
                  release_name: Release ${{ needs.bump_version.outputs.new_tag }}
                  body: |

                      The latest release is always accessible via our alias to the Cloudflare at [app.reflexer.finance](https://app.reflexer.finance).

                      **BEWARE**: The Reflexer app uses [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to remember your settings, such as transactions hashes.

                      ${{ needs.bump_version.outputs.changelog }}
